name: telco-churn-prediction
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - streamlit==1.35.0
      - pandas==2.2.2
      - scikit-learn==1.4.2
      - matplotlib==3.8.4
      - seaborn==0.13.2
      - joblib==1.4.2
      - kaggle==1.6.12
      - catboost==1.2.5
      - optuna==3.6.1
      - tqdm==4.66.4
      - numpy==1.26.4
      - shap==0.45.1
